---
title: "Almond Yield Assignment"
output:
  slidy_presentation:
    highlight: pygments
  html_document: default
  pdf_document: default
  ioslides_presentation:
    highlight: pygments
  beamer_presentation:
    highlight: pygments
---

Submit 
- .R function 
- .RMD
- .html

Your goal is to implement a simple model of almond yield anomaly response to climate
- Inputs: daily times series of minimum, maximum daily temperatures and precipitation
- Outputs: maximum, minimum and mean yield anomoly for a input time series
The Lobell et al. 2006 paper will be the source for the transfer function that you will use in your model; specifically look at the equations in table 2.

Grading 
- a clear diagram that corresponds with your R function (10 pts) 
- inputs and output and parameters shown on the diagram (10 pts)
- correct function implementation (*.R file) (10 pts)
- application of the function to clim.txt (in Rmarkdown file) (10 pts)
- coding practices (clear documentation, informative variables names) (10 pts)

# Draw the Model

# Implement Model in R
- create an R file that has your function definition

```{r}
library(tidyverse)

clim <- read.delim(here::here("assignments", "clim.txt"),
                   header = TRUE,
                   sep = "")

View(clim)

# EQUATION 
T_min = clim$tmin_c

Y_min = (-0.015)*T_min - 0.0046*(T_min^2) - 0.07*P + 0.0043*(P^2) + 0.28
Y_max = (-0.015)*T_min - 0.0046*(T_min^2) - 0.07*P + 0.0043*(P^2) + 0.28
Y_mean = mean(Y_min, Y_max)

```

# Run the Model
- apply the function to the test climate data (clim.txt)

# Check Work

- the maximum almond yield anomaly should be approximately 1920 ton/acre 
- the lowest almond yield anomaly should be approximately -0.027 ton/acre 
- the mean almond yield anomaly should be approximately 182 ton/acre