---
title: "Predator-Prey Assignment"
authors: "Luna Hershenfeld-Catalan"
date: "2024 May 30th"
---

Consider how you might add hunting  of prey to the predator prey model that we've been using in class

# Part 1: Build this model (e.g add hunting to the lotvmodK.R),

Some requirements/hints for your model

- You should make sure that you don't hunt more prey than exist.

- To ensure that you might also add a minimum prey population (`min_prey`) input that must be met before hunting is allowed.

Note you can make this as simple or as complex as you would like. You could represent hunting in a way that is similar to "harvesting" in the last assignment.  A key challenge is how you might want to define stability? It is up to you but you will need to write a sentence to explain why you chose the measure that you did.  It could be something as simple as maintaining a population above some value 50 years into the future. 

```{r}
# initial conditions
currpop=c(prey=1, pred=1)

# set parameter list
pars = c(rprey=0.1, alpha=0.6, eff=0.8, pmort=0.4, K=20, hunt = 1, min_prey = 0)

# times when you want to evaluate
days = seq(from=1, to=500)

lotvmodK_hunt = function(t, pop, pars) {
  
  with(as.list(c(pars,pop)), {
    
    # set minimum condition to allow hunting
    if(prey > min_prey) {
      hunt = hunt
    } else {
      hunt = 0
    }
    
    # subtract the hunted
    dprey = rprey*(1-prey/K)*prey -  alpha*prey*pred - hunt 
    
    dpred = eff*alpha*prey*pred - pmort*pred
    
    return(list(c(dprey,dpred)))
    
  })
}

# run our differential equation solver
res = ode(func=lotvmodK_hunt, y=currpop, times=days, parms=pars)
res
```


Part 2

Explore how different hunting levels and different minimum prey populations (before hunting is allowed) are likely to effect the stability of the populations of both predator and prey.

Use this exploration to recommend a hunting target that will be sustainable (e.g leave you with a stable prey and predator population).

It is up to you how you "explore" hunting  - you can simply try different values of the parameters in your hunting model or do it more formally by running your model across a range of values. You could think about parameter interactions

You can assume the following are best guesses of key parameters

rprey=0.95, alpha=0.01, eff=0.6,pmort=0.4, K=2000,

Submit the Rmarkdown that documents

a) your hunting model

b) your exploration (e.g how you tested different hunting levels and how you defined a stability metric

c) provides you estimated sustainable hunting level. and a few sentences justifying this choice 